import type { Metadata } from 'next';
import { Noto_Sans_TC } from 'next/font/google';
import './globals.css';

import Providers from './providers';

const notoSansTC = Noto_Sans_TC({
  subsets: ['latin'],
  weight: ['400', '700'], // 選你需要的字重
  variable: '--font-noto-sans-tc',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-tw" suppressHydrationWarning>
      <body className={`bg-bg ${notoSansTC.className} antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
