import type { Metadata } from 'next';
import { Noto_Sans_TC } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import MuiThemeProvider from './muiThemeProvider';

import Providers from './providers';

const notoSansTC = Noto_Sans_TC({
  subsets: ['latin'],
  weight: ['400', '700'], // 選你需要的字重
  variable: '--font-noto-sans-tc',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-tw"
      data-theme="light"
      suppressHydrationWarning
    >
      <body className={clsx('bg-theme-bg antialiased', notoSansTC.className)}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <MuiThemeProvider>
            <Providers>
              {children}
            </Providers>
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
